version: '3.7'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.django
      args:
        PIPENV_ARGS:
    ports:
      - '${APP_PORT:-8080}:8080'
    volumes:
      - .:/app
      - ./exports:/app/exports
      - ./media:/app/media
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          memory: 50M
        limits:
          memory: 200M
    networks:
      - app_net

  quasar:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.quasar
    ports:
      - '${NGINX_PORT:-8088}:80'
    volumes:
      - '.:/app'
      - './nginx.conf:/etc/nginx/nginx.conf'
      - './logs:/var/log/nginx/server'
      - './media:/app/media'
    healthcheck:
      test: 'curl -m 5 http://localhost'
      interval: 5s
      timeout: 10s
      start_period: 10s
      retries: 3
    deploy:
      resources:
        reservations:
          memory: 50M
    networks:
      - app_net

  huey:
    build:
      context: .
      dockerfile: Dockerfile.django
    restart: unless-stopped
    volumes:
      - ./:/app
    entrypoint: ['python3', 'manage.py', 'run_huey']
    deploy:
      resources:
        reservations:
          memory: 50M
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
