FROM python:3.11-slim-buster

WORKDIR /app
COPY Pipfile .
COPY Pipfile.lock .
#RUN apt-get update && apt-get install -y gcc ffmpeg
#RUN apt-get update && apt-get install -y git
RUN pip install --no-cache-dir pipenv
RUN pipenv install --system ${PIPENV_ARGS}
COPY . .
RUN ["chmod", "+x", "/app/entrypoint.sh"]
CMD ["/app/entrypoint.sh"]