# Generated by Django 4.1.4 on 2023-11-21 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recycler", "0002_landfill_tickettemplate_company_author_and_more"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="recycler.company",
                verbose_name="Заказчик",
            ),
        ),
    ]
