# Generated by Django 4.2.7 on 2023-11-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("admin", "Админ"),
                    ("buh_inn", "Бухгалтер свой"),
                    ("buh_ext", "Бухгалтер заказчика"),
                    ("outlen", "Отходообразователь"),
                    ("disp", "Диспетчер"),
                    ("otv", "Отвальщик"),
                    ("man", "Менеджер"),
                ],
                max_length=10,
                null=True,
                verbose_name="Роль",
            ),
        ),
    ]
