# Generated by Django 5.0 on 2024-02-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("admin", "Админ"),
                    ("buh_inn", "Бухгалтер свой"),
                    ("buh_ext", "Бухгалтер заказчика"),
                    ("outlen", "Отходообразователь"),
                    ("disp", "Диспетчер"),
                    ("otv", "Отвальщик"),
                    ("man", "Мастер участка"),
                ],
                max_length=10,
                null=True,
                verbose_name="Роль",
            ),
        ),
    ]
