# Generated by Django 4.2.7 on 2023-11-20 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата редактирования"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "status",
                    models.CharField(
                        choices=[("cr", "Создан"), ("re", "Готов к работе")],
                        default="cr",
                        max_length=2,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "customer",
                    models.CharField(blank=True, max_length=100, null=True, verbose_name="Заказчик"),
                ),
                (
                    "contract_num",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Номер договора",
                    ),
                ),
                (
                    "sum_actual",
                    models.FloatField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Сумма фактическая",
                    ),
                ),
                (
                    "sum_overall",
                    models.FloatField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Сумма общая",
                    ),
                ),
            ],
            options={
                "verbose_name": "Компания",
                "verbose_name_plural": "Компании",
            },
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата редактирования"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("cr", "Создан"), ("ar", "Архив")],
                        default="cr",
                        max_length=2,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "car_num",
                    models.CharField(max_length=100, verbose_name="Номер машины"),
                ),
                ("mass_full", models.FloatField(verbose_name="Масса полная")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recycler.company",
                        verbose_name="Компания",
                    ),
                ),
            ],
            options={
                "verbose_name": "Талон",
                "verbose_name_plural": "Талоны",
            },
        ),
        migrations.CreateModel(
            name="FKKO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата редактирования"),
                ),
                ("code", models.CharField(max_length=100, verbose_name="Код")),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Наименование кода"),
                ),
                (
                    "security_class",
                    models.CharField(max_length=100, verbose_name="Класс безопасности"),
                ),
                ("price", models.FloatField(verbose_name="Стоимость")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fkko",
                        to="recycler.company",
                        verbose_name="Компания",
                    ),
                ),
            ],
            options={
                "verbose_name": "ФККО",
                "verbose_name_plural": "ФККО",
            },
        ),
        migrations.CreateModel(
            name="CompanyContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата редактирования"),
                ),
                ("file", models.FileField(upload_to="", verbose_name="Файл договора")),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to="recycler.company",
                        verbose_name="Компания",
                    ),
                ),
            ],
            options={
                "verbose_name": "Контракт",
                "verbose_name_plural": "Контракты",
            },
        ),
    ]
