# Generated by Django 4.1.4 on 2023-11-21 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recycler", "0002_landfill_tickettemplate_company_author_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tickettemplate",
            name="car_num",
            field=models.CharField(default=None, max_length=100, verbose_name="Номер машины"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tickettemplate",
            name="company",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ticket_template",
                to="recycler.company",
                verbose_name="Шаблон тикета",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tickettemplate",
            name="fkko",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="recycler.fkko",
                verbose_name="ФККО",
            ),
        ),
        migrations.AddField(
            model_name="tickettemplate",
            name="mass_full",
            field=models.FloatField(default=None, verbose_name="Масса полная"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ticket",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="recycler.company",
                verbose_name="Компания",
            ),
        ),
    ]
