# Generated by Django 4.1.4 on 2023-11-21 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recycler", "0003_tickettemplate_car_num_tickettemplate_company_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="company",
        ),
        migrations.AlterField(
            model_name="tickettemplate",
            name="company",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ticket_template",
                to="recycler.company",
                verbose_name="Компания",
            ),
        ),
    ]
