# Generated by Django 4.2.7 on 2023-11-28 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recycler", "0004_remove_ticket_company_alter_tickettemplate_company"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={"ordering": ["-created_at"], "verbose_name": "Талон", "verbose_name_plural": "Талоны"},
        ),
    ]
