# Generated by Django 4.1.4 on 2023-11-29 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recycler", "0005_alter_ticket_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="company",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="recycler.company",
                verbose_name="Компания",
            ),
            preserve_default=False,
        ),
    ]
