# Generated by Django 4.1.4 on 2023-11-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recycler", "0006_ticket_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="mass_full",
            field=models.FloatField(null=True, verbose_name="Масса полная"),
        ),
        migrations.AlterField(
            model_name="tickettemplate",
            name="mass_full",
            field=models.FloatField(null=True, verbose_name="Масса полная"),
        ),
    ]
