# Generated by Django 4.2.7 on 2023-12-01 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recycler", "0007_alter_ticket_mass_full_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="car_model",
            field=models.CharField(blank=True, max_length=100, verbose_name="Номер машины"),
        ),
        migrations.AddField(
            model_name="ticket",
            name="short_name",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Отход кратко"),
        ),
        migrations.AlterField(
            model_name="fkko",
            name="security_class",
            field=models.CharField(max_length=100, verbose_name="Класс опасности"),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="car_num",
            field=models.CharField(blank=True, max_length=100, verbose_name="Номер машины"),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="mass_full",
            field=models.FloatField(blank=True, null=True, verbose_name="Масса полная"),
        ),
        migrations.AlterField(
            model_name="tickettemplate",
            name="car_num",
            field=models.CharField(blank=True, max_length=100, verbose_name="Номер машины"),
        ),
        migrations.AlterField(
            model_name="tickettemplate",
            name="fkko",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="recycler.fkko",
                verbose_name="ФККО",
            ),
        ),
        migrations.AlterField(
            model_name="tickettemplate",
            name="mass_full",
            field=models.FloatField(blank=True, null=True, verbose_name="Масса полная"),
        ),
    ]
