# Generated by Django 4.2.7 on 2023-12-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recycler", "0008_ticket_car_model_ticket_short_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="num",
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name="Номер талона"),
        ),
    ]
