# Generated by Django 4.2.7 on 2023-12-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recycler", "0009_ticket_num"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("cr", "Создан"),
                    ("pr", "В обработке"),
                    ("ar", "Архив"),
                    ("nc", "Несоответствие"),
                    ("er", "Ошибка"),
                ],
                default="cr",
                max_length=2,
                verbose_name="Статус",
            ),
        ),
    ]
