# Generated by Django 4.2.7 on 2023-12-18 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recycler", "0010_alter_ticket_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="landfill",
            options={"verbose_name": "Наименование площадки", "verbose_name_plural": "Наименование площадок"},
        ),
        migrations.AddField(
            model_name="ticket",
            name="landfill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="recycler.landfill",
                verbose_name="Наименование площадки",
            ),
        ),
    ]
