# Generated by Django 4.2.7 on 2023-12-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recycler", "0011_alter_landfill_options_ticket_landfill"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="approve_status",
            field=models.BooleanField(null=True, verbose_name="Статус подтверждения"),
        ),
    ]
