# Generated by Django 4.2.7 on 2023-12-24 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recycler", "0012_ticket_approve_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="fkko",
            name="contract",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fkko",
                to="recycler.companycontract",
                verbose_name="Контракт",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="num",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name="Номер талона"),
        ),
    ]
