# Generated by Django 5.0 on 2023-12-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recycler", "0013_fkko_contract_alter_ticket_num"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fkko",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Наименование кода"),
        ),
        migrations.AlterField(
            model_name="fkko",
            name="security_class",
            field=models.CharField(blank=True, max_length=100, verbose_name="Класс опасности"),
        ),
        migrations.AlterUniqueTogether(
            name="fkko",
            unique_together={("code", "company")},
        ),
    ]
