# Generated by Django 5.0 on 2023-12-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recycler", "0014_alter_fkko_name_alter_fkko_security_class_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="contract_date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата договора"),
        ),
    ]
