# Generated by Django 5.0 on 2024-01-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recycler", "0015_company_contract_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="mass_empty",
            field=models.FloatField(blank=True, null=True, verbose_name="Масса пустая"),
        ),
        migrations.AddField(
            model_name="tickettemplate",
            name="mass_empty",
            field=models.FloatField(blank=True, null=True, verbose_name="Масса пустая"),
        ),
    ]
