# Generated by Django 5.0 on 2024-01-14 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recycler", "0016_ticket_mass_empty_tickettemplate_mass_empty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="num",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name="Номер талона"),
        ),
    ]
