# Generated by Django 5.0 on 2024-02-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recycler", "0017_alter_ticket_num"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="waste_image",
            field=models.ImageField(blank=True, null=True, upload_to="", verbose_name="Фото отхода"),
        ),
    ]
