# Generated by Django 5.0 on 2024-02-03 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recycler", "0018_ticket_waste_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="landfill",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="companies",
                to="recycler.landfill",
                verbose_name="Наименование площадки",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="landfill",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="recycler.landfill",
                verbose_name="Наименование площадки",
            ),
        ),
    ]
