# Generated by Django 5.0 on 2024-10-30 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycler', '0019_company_landfill_alter_ticket_landfill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='landfill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='recycler.landfill', verbose_name='Наименование площадки'),
        ),
    ]
