# Generated by Django 5.0 on 2024-11-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycler', '0020_alter_company_landfill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('cr', 'Создан'), ('pr', 'В обработке'), ('ar', 'Архив'), ('nc', 'Несоответствие'), ('er', 'Ошибка'), ('pn', 'На выгрузке')], default='cr', max_length=2, verbose_name='Статус'),
        ),
    ]
