# Generated by Django 5.0 on 2024-11-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycler', '0021_alter_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='kpts',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='КПТС'),
        ),
        migrations.AlterField(
            model_name='company',
            name='customer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ИНН'),
        ),
    ]
