# Generated by Django 5.0 on 2024-11-15 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycler', '0022_company_kpts_alter_company_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noncompliancereport',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noncompliance_reports', to='recycler.ticket', verbose_name='Талон'),
        ),
    ]
